### ISSUE TITLE
Working in web workers

### ISSUE THREAD

**Issue by nksaraf** [mizchi/uniroll#5]
Hi, I was trying to integrate this in a developer sandbox tool I was building, and needed to make it work in a web worker, but I was unable to. I think there are reference to localStorage being used that make it not possible to use in web workers. Is there way to make it work with workers.

**Comment by mizchi** [comment]
Sorry for late.
worker can not touch localStorage. Please use https://developer.mozilla.org/ja/docs/Web/API/IndexedDB_API
